version: "2"
plugins:
  duplication:
    enabled: true
      - mass = 50
    config:
      languages:
         python:
           mass_threshold: 40
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_patterns: 
- "wafo/tests/"
- "wafo/MSPPT.py"
- "wafo/MSO.py"